### ISSUE TITLE
promises example?

### ISSUE THREAD

**Issue by hifilorau** [petermoresi/react-download-link#1]
Hey Peter, 

Do you by chance have any examples of where you have used this with a promise? I'm trying to fire off an event once the file has downloaded but am losing my file contents once i pass my own function into export ie 

`export={this.createFile.bind(this)}`

Not sure i fully grok how the promise resolve works in your example and feel like if i could see it in action it might help.

Thanks, and great easy to use component by the way!

**Comment by petermoresi** [comment]
Hi,

I'm just seeing this message now. I hope you figured out a solution by now.

The example is a thunk that returns a resolved promise. You should be able to do:

``` js
export={ () => this.createFile() }
```

The relevant section in the code that uses the promise:

``` js
    if (text instanceof Promise) {
      text.then(
        result => magicDownload(result, this.props.filename)
      )
    } else {
      magicDownload(text, this.props.filename)
    }
```

Thanks for the feedback. This component needs a little work and better tests ;)
